package ajuapp.database;

public class TablesFields {
    public enum PERSON {PERSON_ID, FIRST_NAME, LAST_NAME, USER_NAME, PASSWORD};
    public enum ADMIN {ADMIN_ID, PERSON_ID, ID};
    public enum STUDENT {STUDENT_ID, PERSON_ID, ACADEMIC_ID, ID};
    public enum PROFESSOR {PROFESSOR_ID, PERSON_ID, ACADEMIC_ID, ID};
    public enum ACADEMIC {ACADEMIC_ID, COURSE1_ID, COURSE2_ID, COURSE3_ID, COURSE4_ID, COURSE5_ID, COURSE6_ID};
    public enum COURSE {COURSE_ID, COURSE_NAME, PRICE};
}


